import { defineArrayMember, defineField, defineType } from "sanity";

export const aboutPage = defineType({
  name: "aboutPage",
  title: "About page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero", default: true },
    { name: "stats", title: "Stats" },
    { name: "sections", title: "Section headings" },
    { name: "cta", title: "CTA" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "heroName",
      type: "string",
      group: "hero",
      description: "Large animated name, e.g. 'Akash Sharma'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroTags",
      title: "Tags",
      type: "array",
      group: "hero",
      description: "Short badges under the name, e.g. 'Builder by Practice'.",
      of: [defineArrayMember({ type: "string" })],
      validation: (r) => r.required().min(1).max(4).warning("More than 4 tags starts to wrap awkwardly."),
    }),
    defineField({
      name: "heroBio",
      type: "text",
      rows: 4,
      group: "hero",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroCtaPrimaryLabel",
      type: "string",
      group: "hero",
      description: "Links to /projects, e.g. 'See my work →'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroCtaSecondaryLabel",
      type: "string",
      group: "hero",
      description: "Links to /contact, e.g. 'Get in touch'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "stats",
      type: "array",
      group: "stats",
      of: [
        defineArrayMember({
          type: "object",
          name: "stat",
          fields: [
            defineField({ name: "value", type: "string", validation: (r) => r.required() }),
            defineField({ name: "label", type: "string", validation: (r) => r.required() }),
          ],
          preview: { select: { title: "value", subtitle: "label" } },
        }),
      ],
      validation: (r) => r.required().min(1),
    }),
    defineField({
      name: "experienceEyebrow",
      type: "string",
      group: "sections",
      description: "e.g. 'How I got here'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "experienceHeading",
      type: "string",
      group: "sections",
      description: "e.g. 'My Journey.'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "techEyebrow",
      type: "string",
      group: "sections",
      description: "e.g. 'Tools of the trade'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "techHeading",
      type: "string",
      group: "sections",
      description: "e.g. 'Tech Stack.'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "ctaEyebrow",
      type: "string",
      group: "cta",
      description: "e.g. 'What's next'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "ctaHeadingLine1",
      type: "string",
      group: "cta",
      description: "e.g. 'Let's build something'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "ctaHeadingHighlight",
      type: "string",
      group: "cta",
      description: "Highlighted word/phrase on its own line, e.g. 'remarkable.'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "ctaBody",
      type: "text",
      rows: 3,
      group: "cta",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "ctaPrimaryLabel",
      type: "string",
      group: "cta",
      description: "Links to /contact, e.g. 'Get in touch'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "ctaSecondaryLabel",
      type: "string",
      group: "cta",
      description: "Links to /projects, e.g. 'See projects'.",
      validation: (r) => r.required(),
    }),
    defineField({ name: "seo", type: "seo", group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "About page" }) },
});
