import { defineArrayMember, defineField, defineType } from "sanity";

// Fixed-documentId singleton (AK-SAN-036) — one Home page, opened directly.
export const homePage = defineType({
  name: "homePage",
  title: "Home page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero", default: true },
    { name: "about", title: "About section" },
    { name: "sections", title: "Section headings" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Eyebrow",
      type: "string",
      group: "hero",
      description: "Small label above the heading, e.g. 'Full-Stack Developer · Available for hire'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroGreeting",
      title: "Greeting",
      type: "string",
      group: "hero",
      description: "Text before the name, e.g. 'Hi, I'm'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroName",
      title: "Name",
      type: "string",
      group: "hero",
      description: "Shown highlighted, e.g. 'Akash.'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroSubheadLine1",
      title: "Subheading — line 1",
      type: "string",
      group: "hero",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroSubheadLine2",
      title: "Subheading — line 2",
      type: "text",
      rows: 3,
      group: "hero",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroCtaPrimaryLabel",
      title: "Primary button label",
      type: "string",
      group: "hero",
      description: "Links to /projects, e.g. 'See my work →'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroCtaSecondaryLabel",
      title: "Secondary button label",
      type: "string",
      group: "hero",
      description: "Links to /contact, e.g. 'Get in touch'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "aboutEyebrow",
      type: "string",
      group: "about",
      description: "e.g. 'Who I am'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "aboutHeading",
      type: "string",
      group: "about",
      description: "e.g. 'Akash Sharma.'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "aboutBody",
      type: "text",
      rows: 4,
      group: "about",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "aboutCtaLabel",
      title: "About CTA label",
      type: "string",
      group: "about",
      description: "Links to /about, e.g. 'More about me →'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "aboutStats",
      title: "Stats",
      type: "array",
      group: "about",
      of: [
        defineArrayMember({
          type: "object",
          name: "stat",
          fields: [
            defineField({ name: "value", type: "string", validation: (r) => r.required() }),
            defineField({ name: "label", type: "string", validation: (r) => r.required() }),
          ],
          preview: { select: { title: "value", subtitle: "label" } },
        }),
      ],
      validation: (r) => r.required().min(1),
    }),
    defineField({
      name: "featuredProjectsEyebrow",
      type: "string",
      group: "sections",
      description: "e.g. 'What I've built'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "featuredProjectsHeading",
      type: "string",
      group: "sections",
      description: "e.g. 'Featured Projects.'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "featuredProjectsViewAllLabel",
      type: "string",
      group: "sections",
      description: "Links to /projects, e.g. 'View all →'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "testimonialsEyebrow",
      type: "string",
      group: "sections",
      description: "e.g. 'Kind words'.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "testimonialsHeading",
      type: "string",
      group: "sections",
      description: "e.g. 'What people say.'.",
      validation: (r) => r.required(),
    }),
    defineField({ name: "seo", type: "seo", group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "Home page" }) },
});
